services:
  app:
    container_name: korrk_backend
    restart: always
    build: .
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - korrk_postgres

  korrk_postgres:
    image: postgis/postgis:16-3.5
    container_name: korrk_postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: 'UTC'
      PGTZ: 'UTC'
      PGPORT: '5433'
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/korrk/data
volumes:
  postgres-data:
